const storeAction = {
    CART_INIT : 'CART_INIT',
    CART_ADD: 'ADD',
    CARD_REMOVE: 'REMOVE',
    CARD_UPDATE: 'CARD_UPDATE',
    PRODUCT_FILTER: 'PRODUCT_FILTER',
    PRODUCT_INIT: 'PRODUCT_INIT',
    COMPANY_INIT: 'COMPANY_INIT',
    ORDER_INIT:'ORDER_INIT',
    DONATE_INIT:'DONATE_INIT',
    COMPANY_CHANGE: 'COMPANY_CHANGE'
}

export default storeAction
